### ISSUE TITLE
Error: Cannot find module 'ipaddr.js' during yarn run dev

### ISSUE THREAD

**Issue by meonkeys** [streamplace/wheelhouse#82]
This is using node v6.10.3 (npm v3.10.10).

```
✨ [adamm@stu wheelhouse <optional-browser-opn=>]$ yarn run dev
yarn run v0.24.5
$ DEBUG='wheelhouse:*' lerna exec --concurrency=999 --no-sort yarn run dev 
lerna info version 2.0.0-rc.5
yarn run v0.24.5
yarn run v0.24.5
yarn run v0.24.5
$ babel --retain-lines -w -s -d dist src 
$ npm run prepublish && npm link && WH_LOCAL_DEV=true babel -s -d dist -w src 
$ BROWSER=none PORT=3942 react-scripts start --color=always | cat 
module.js:471
    throw err;
    ^

Error: Cannot find module 'ipaddr.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/adamm/git/streamplace/wheelhouse/packages/wheelhouse-frontend/node_modules/proxy-addr/index.js:24:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Done in 0.41s.

> wheelhouse@0.1.14 prepublish /home/adamm/git/streamplace/wheelhouse/packages/wheelhouse
> babel -d dist src
```

**Comment by iameli** [comment]
I'm thinking this has to be node 4 not liking the way Yarn installs dependencies.

`nvm use 6` would probably be a workaround for now. The resulting `wheelhouse` module needs to work in node 4, but maybe for now node 6 is necessary to run the development environment.

**Comment by meonkeys** [comment]
This _is_ using node v6.10.3 (npm v3.10.10).

**Comment by meonkeys** [comment]
hmm, `npm install` and `npm run dev` don't spit out that "Cannot find module 'ipaddr.js'" error

**Comment by iameli** [comment]
Yeah, worked around with `npm run dev` and I'll update the docs to say that.

**Comment by iameli** [comment]
I'm keeping this open under the label "weirdness happening in the dev environment"

**Comment by iameli** [comment]
Yarn has been removed from the project, so I'm hoping this is resolved.
