### ISSUE TITLE
Loading `/#/development` directly leads to various problems

### ISSUE THREAD

**Issue by iameli** [streamplace/wheelhouse#86]
I've gotten reports of this from @megelismi and @chase.maier and @tyleha but for the life of me haven't been able to reproduce it yet. Something just doesn't get initalized properly when you navigate straight to this page, but not always... some kind of race condition. Here's @tyleha's error

 ```
Uncaught (in promise) Error: 'autoDismiss' must be a number.
    at Object.addNotification (http://localhost:2999/static/js/main.5f0b2078.js:11:4108)
    at http://localhost:2999/static/js/main.5f0b2078.js:7:19992
    at Array.forEach (native)
    at e.value (http://localhost:2999/static/js/main.5f0b2078.js:7:19950)
    at t.notifyAll (http://localhost:2999/static/js/main.5f0b2078.js:4:320)
    at r.close (http://localhost:2999/static/js/main.5f0b2078.js:10:10820)
    at r.closeAll (http://localhost:2999/static/js/main.5f0b2078.js:2:13715)
    at r.perform (http://localhost:2999/static/js/main.5f0b2078.js:2:13204)
    at u (http://localhost:2999/static/js/main.5f0b2078.js:4:7004)
    at r.perform (http://localhost:2999/static/js/main.5f0b2078.js:2:13121)```
```

Something to do with server notifications, then? Unsure.

**Comment by iameli** [comment]
Seems like whatever's causing this, we can solve it just be being very careful to make `autoDismiss` a number in all circumstances.
